# -*- coding: utf-8 -*-
"""Asssignment10_cse_202151124.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvMB5gGOKrcL65ha-nUxRPKqlVt8S7zQ
"""

# Name: Raghav Agiwal
# ID: 202151124
# Assignment 10

# Importing necessary libraries
import pandas as pd
import random
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy import stats

# Importing specific functions from scipy.stats
from scipy.stats import ttest_ind
from scipy.stats import chi2_contingency

# Reading data
cookie_df = pd.read_csv("cookie_cats.csv")  # Reading the cookie data from the CSV file
auction_df = pd.read_csv("IPL_Auction_2022_FullList.csv")  # Reading the auction data from the CSV file

# Extracting data for analysis
cookie_gate_30 = cookie_df[cookie_df["version"] == "gate_30"]["sum_gamerounds"]  # Selecting game rounds data for version gate_30
cookie_gate_40 = cookie_df[cookie_df["version"] == "gate_40"]["sum_gamerounds"]  # Selecting game rounds data for version gate_40

# Performing t-test
t_stat, p_value = ttest_ind(cookie_gate_30, cookie_gate_40)  # Performing independent t-test

print("T-Statistic:", t_stat)  # Printing the calculated t-statistic
print("P-Value:", p_value)  # Printing the calculated p-value

alpha = 0.05  # Setting the significance level
if p_value < alpha:  # Checking if the p-value is less than alpha
    print("The analysis suggests a significant difference in the average number of game rounds played between gate_30 and gate_40.")
else:
    print("There is insufficient evidence to conclude a significant difference in the average number of game rounds played between gate_30 and gate_40.")

# Performing chi-square test
selected_data = auction_df[["Specialism", "Batting"]]  # Selecting specific columns for analysis
contingency_table = pd.crosstab(selected_data["Specialism"], selected_data["Batting"])  # Creating a contingency table

print("\nContingency Table:")  # Printing the contingency table
print(contingency_table)

chi2, p, dof, expected = chi2_contingency(contingency_table)  # Performing chi-square test
print("\nChi-Square Statistic:", chi2)  # Printing the calculated chi-square statistic
print("P-Value:", p)  # Printing the calculated p-value
print("Degrees of Freedom:", dof)  # Printing the degrees of freedom
print("\nExpected Frequencies:")  # Printing the expected frequencies
print(expected)

alpha = 0.05  # Setting the significance level
if p < alpha:  # Checking if the p-value is less than alpha
    print("\nThe null hypothesis is rejected: There is a significant association between Specialism and Batting type.")
else:
    print("\nThe null hypothesis cannot be rejected: No significant association is found between Specialism and Batting type.")

"""# New Section"""