# -*- coding: utf-8 -*-
"""Assignment1-CS-202151124.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cX9VNg8lLmVA7WR7PXyFQT1o3hF3rmKj
"""

import json
import pandas as pd

#202151124
#Raghav Agiwal
#Assignment 1


#Q1 Task 1: Reading and Loading Data


# Reading the CSV file
df_1= pd.read_csv("district_level_service_msme.csv")
# Reading the JSON file
filepath = 'district_level_manufacturing_msme.json'
f = open(filepath)
data=json.load(f)
df_2=pd.DataFrame(data["data"])
# Extracting column labels
cols =[ x["label"] for x in data["fields"]]
df_2=pd.DataFrame(data["data"],columns = cols)
print(df_1)
print(df_2)

#Q2 Task 2: Total SMALL Manufacturing MSME
total_small= df_1["SMALL"].sum() # Calculating the total count
print(total_small)

#Q3 Task 3: State-wise Service MSME
custom_df_1 = df_1.groupby(by= "STATE_NAME").sum()["MICRO"]
custom_df_2 = df_1.groupby(by= "STATE_NAME").sum()["SMALL"]
custom_df_3 = df_1.groupby(by= "STATE_NAME").sum()["MEDIUM"]

df_3= pd.concat([custom_df_1,custom_df_2,custom_df_3],axis = 1)
print(df_3)


#Q4 Task 4: Merging DataFrames
df_1["Lg_Dist_Code"]=df_1["Lg_Dist_Code"].astype(str)
df_1["Last_Updated"]=df_1["Last_Updated"].astype(str)
merged_df = pd.merge(df_1, df_2, on=['STATE_NAME','DISTRICT_NAME','Lg_Dist_Code', 'Last_Updated'], suffixes=('_x', '_y'))
print(merged_df)


#Q5  Task 5: Pivot and Merge
merged_df["MICRO_y"]=merged_df["MICRO_y"].astype(int)
merged_df["SMALL_y"]=merged_df["SMALL_y"].astype(int)
merged_df["MEDIUM_y"]=merged_df["MEDIUM_y"].astype(int)
final_table = merged_df.pivot_table(values=['MICRO_x','SMALL_x','MEDIUM_x','MICRO_y','SMALL_y','MEDIUM_y'],index='STATE_NAME',aggfunc='sum')
print(final_table)